const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const { mkdtempSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { join } = require('node:path');
process.env.ACCOUNT_STORE_DIR = mkdtempSync(join(tmpdir(), 'blue-maruya-auth-test-'));
delete process.env.VERCEL;
process.env.AUTH_SESSION_SECRET = crypto.randomBytes(32).toString('hex');
const handler = require('../api/auth');
const tmdb = require('../api/tmdb');
const { getSession } = require('../lib/session');
const origin = 'https://bluemaruya.vercel.app';
const headers = { host: 'bluemaruya.vercel.app', origin, 'content-type': 'application/json', 'x-forwarded-proto': 'https' };
async function call(method, body, extra = {}, fn = handler) {
  const req = { method, body, query: {}, headers: { ...headers, ...extra } };
  const res = { headers: {}, setHeader(key, value) { this.headers[key] = value; }, end(value) { this.body = JSON.parse(value); } };
  await fn(req, res);return res;
}
(async()=>{
  assert.equal((await call('GET')).body.authenticated, false);
  assert.equal((await call('GET', null, {}, tmdb)).statusCode, 401);
  assert.equal((await call('POST', { username: 'someone', password: 'wrong' })).statusCode, 401);
  const password = process.env.TEST_LOGIN_PASSWORD;
  assert.ok(password, 'TEST_LOGIN_PASSWORD is required');
  assert.equal((await call('POST', { username: 'someone', password })).statusCode, 401);
  const valid = await call('POST', { username: 'wakengwapo', password });
  assert.equal(valid.statusCode, 200);
  const cookie = valid.headers['Set-Cookie'];
  assert.equal(valid.body.displayName, 'waken');
  assert.match(cookie, /HttpOnly/);assert.match(cookie, /SameSite=Strict/);assert.match(cookie, /Secure/);
  assert.equal(valid.headers['Cache-Control'], 'no-store');
  assert.equal((await call('GET', null, {cookie})).body.authenticated, true);
  assert.equal((await call('GET', null, {cookie:cookie.replace('blue_maruya_session=', 'blue_maruya_session=x')})).body.authenticated, false);
  const expired = Buffer.from(JSON.stringify({ user: 'wakengwapo', exp: 1 })).toString('base64url');
  const key = Buffer.from(crypto.hkdfSync('sha256', process.env.AUTH_SESSION_SECRET, 'blue-maruya-v1', 'member-session', 32));
  const sig = crypto.createHmac('sha256', key).update(expired).digest('base64url');
  assert.equal(getSession({headers:{cookie:'blue_maruya_session='+expired+'.'+sig}}),null);
  assert.equal((await call('POST', {username:'wakengwapo',password},{origin:'https://example.com'})).statusCode,403);
  assert.equal((await call('DELETE', null, {origin:'https://example.com'})).statusCode,403);
  assert.match((await call('DELETE')).headers['Set-Cookie'],/Max-Age=0/);
  assert.equal((await call('POST',{}, {'content-type':'text/plain'})).statusCode,415);
  assert.equal((await call('POST',{}, {'content-length':'9000'})).statusCode,413);
  const secondPassword = process.env.TEST_SECOND_PASSWORD;
  assert.ok(secondPassword, 'TEST_SECOND_PASSWORD is required');
  const second = await call('POST', { username: 'kdumangas', password: secondPassword });
  assert.equal(second.statusCode, 200); assert.equal(second.body.displayName, 'kristine');
  const secondCookie = second.headers['Set-Cookie'];
  assert.equal((await call('POST', { username: 'kdumangas', password })).statusCode, 401);
  assert.equal((await call('POST', { username: 'wakengwapo', password: secondPassword })).statusCode, 401);
  assert.equal((await call('PATCH', {action:'profile', displayName:'No account'})).statusCode, 401);
  assert.equal((await call('PATCH', {action:'profile', displayName:'<script>'}, {cookie})).statusCode, 400);
  assert.equal((await call('PATCH', {action:'profile', displayName:'Name'}, {cookie, origin:'https://example.com'})).statusCode, 403);
  const renamed = await call('PATCH', { action:'profile', displayName:'Waken Cinema', username:'kdumangas' }, {cookie});
  assert.equal(renamed.statusCode, 200); assert.equal(renamed.body.username, 'wakengwapo');
  assert.equal((await call('GET', null, {cookie})).body.displayName, 'Waken Cinema');
  assert.equal((await call('GET', null, {cookie:secondCookie})).body.displayName, 'kristine');
  assert.equal((await call('POST', {username:'wakengwapo',password})).body.displayName, 'Waken Cinema');
  assert.equal((await call('PATCH', {action:'password', currentPassword:'wrong', newPassword:crypto.randomBytes(12).toString('hex')}, {cookie})).statusCode, 400);
  assert.equal((await call('PATCH', {action:'password', currentPassword:password, newPassword:'short'}, {cookie})).statusCode, 400);
  const { readMember, writeMember } = require('../lib/members');
  const before = await readMember('wakengwapo');
  const changedPassword = crypto.randomBytes(24).toString('base64url');
  const changed = await call('PATCH', {action:'password', currentPassword:password, newPassword:changedPassword}, {cookie});
  assert.equal(changed.statusCode, 200);
  const changedCookie = changed.headers['Set-Cookie'];
  assert.equal((await call('GET', null, {cookie})).body.authenticated, false);
  assert.equal((await call('GET', null, {cookie:changedCookie})).body.authenticated, true);
  assert.equal((await call('GET', null, {cookie}, tmdb)).statusCode, 401);
  assert.equal((await call('POST', {username:'wakengwapo',password})).statusCode, 401);
  assert.equal((await call('POST', {username:'wakengwapo',password:changedPassword})).statusCode, 200);
  assert.equal((await call('POST', {username:'kdumangas',password:secondPassword})).statusCode, 200);
  await assert.rejects(writeMember(before.member, before.etag), error => error.status === 409);
  assert.equal((await call('PATCH', {action:'profile', displayName:'Old session'}, {cookie})).statusCode, 401);
  assert.ok(!JSON.stringify(changed.body).includes('hash'));
  for(let i=0;i<8;i++)assert.equal((await call('POST',{username:'bad',password:'bad'},{'x-forwarded-for':'test-rate-limit'})).statusCode,401);
  assert.equal((await call('POST',{username:'bad',password:'bad'},{'x-forwarded-for':'test-rate-limit'})).statusCode,429);
  console.log('PASS: both accounts, isolated profiles, persistent name/password changes, old-password rejection, session revocation, concurrent-write protection, cookie security, origin checks, throttling, and private catalog.');
})().catch(error=>{console.error(error);process.exitCode=1;});
