const assert = require('node:assert/strict');
const { create } = require('../dist/watch-history');
const data = new Map();
const storage = {getItem:key=>data.get(key)||null,setItem:(key,value)=>data.set(key,value)};
const history = create(storage);
const movie = {id:808,type:'movie',title:'Shrek',year:2001,image:'preference-shrek.jpg'};
assert.deepEqual(history.read('wakengwapo'),[]);
assert.equal(history.record('wakengwapo',movie,1,1,1000),true);
assert.deepEqual(history.read('kdumangas'),[]);
assert.equal(history.record('kdumangas',{...movie,id:38757,title:'Tangled'},1,1,2000),true);
assert.equal(history.read('wakengwapo')[0].title,'Shrek');
assert.equal(history.record('wakengwapo',{...movie,title:'Shrek again'},1,1,3000),true);
assert.equal(history.read('wakengwapo').length,1);
assert.equal(history.read('wakengwapo')[0].watchedAt,3000);
history.record('wakengwapo',{...movie,id:1396,type:'tv',title:'Breaking Bad',seasons:[7,13,13,13,16]},3,5,4000);
const restored = create(storage).read('wakengwapo')[0];
assert.equal(restored.season,3);assert.equal(restored.episode,5);assert.equal(restored.type,'tv');
for(let index=1;index<40;index++)history.record('wakengwapo',{...movie,id:10000+index},1,1,5000+index);
assert.equal(history.read('wakengwapo').length,24);
assert.equal(history.read('wakengwapo')[0].id,10039);
assert.equal(history.remove('kdumangas',{id:38757,type:'movie'}),true);
assert.equal(history.read('kdumangas').length,0);assert.equal(history.read('wakengwapo').length,24);
assert.throws(()=>history.read('guest'));
data.set('blue-maruya-history:kdumangas','broken-json');assert.deepEqual(history.read('kdumangas'),[]);
data.set('blue-maruya-history:kdumangas',JSON.stringify([{...movie,image:'javascript:alert(1)',watchedAt:99},{type:'movie',id:-1,title:'Invalid'},null]));
assert.equal(history.read('kdumangas').length,1);assert.equal(history.read('kdumangas')[0].image,'');
const denied = create({getItem(){throw new Error('Blocked');},setItem(){throw new Error('Full');}});
assert.deepEqual(denied.read('wakengwapo'),[]);assert.equal(denied.record('wakengwapo',movie),false);
console.log('PASS history: account isolation, reload persistence, newest-first order, deduplication, episode resume, 24-item limit, removal, invalid-data handling, and unavailable storage.');
